baseURL = '/'
languageCode = 'en-us'
title = 'ErrorPro(黃乙家)'


[permalinks]
posts = "/posts/:year/:filename/"

# Navigation
## Main menu which appears below site header.
[[menu.main]]
name = "主頁"
url = "/"
weight = 1


[[menu.main]]
name = "廢文區"
url = "/posts"
weight = 2

[[menu.main]]
name = "資源"
url = "/resources"
weight = 3


[[menu.main]]
name = "標籤"
url = "/tags"
weight = 4

[[menu.main]]
name = "關於本人"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

    colortheme = "white" # dark, light, white, or classic
	googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  
    # Home page settings
    description = "我不會寫程式啊"
    mainSection = "posts" # your main section
    showAllPostsOnHomePage = false
    postsOnHomePage = 10
    tagsOverview = true
    # showProjectsList = true # show projects list by default (if projects data file exists).
    # projectsUrl = "https://github.com/gohugoio" # title link for projects list
    showAllPostsArchive = false
  
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02" # default
  
    # Post page settings
    show_updated = false # default
    defaultAuthor = "ErrorPro"

    mathjax = true
    css = ["css/highlight.css", "css/style-dark.css", "css/search.css"]
  
    [params.comments]
    enabled = false # default
    engine = "utterances" # more supported engines will be added.
	  
  
    # the value of name should be an valid font awesome icon name (brands type)
    # https://fontawesome.com/icons?d=gallery&s=brands

    [[params.social]]
    name = "facebook"
    link = "test"
    [[params.social]]
    name = "github"
    link = "test"
    [[params.social]]
    name = "email"
    link = "u810025@gmail.com"  # no need for "mailto:" in the head
[outputs]
    home = ["HTML", "RSS", "JSON"]
