baseURL = '/'
languageCode = 'zh-Hant-TW'
title = 'ErrorPro'
theme = "cactus"
timeZone = "Asia/Taipei"

[permalinks]
posts = "/posts/:year/:filename/"

# Navigation
## Main menu which appears below site header.
[[menu.main]]
name = "主頁"
url = "/"
weight = 1


[[menu.main]]
name = "廢文區"
url = "/posts"
weight = 2

[[menu.main]]
name = "資源"
url = "/resources"
weight = 3


[[menu.main]]
name = "標籤"
url = "/tags"
weight = 4

[[menu.main]]
name = "留言區"
url = "/comment"
weight = 5

[[menu.main]]
name = "關於本人"
url = "/about"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

    colortheme = "dark" # dark, light, white, or classic
	googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  
    # Home page settings
    description = "我覺得現在在看這句話的人超電"
    mainSection = "posts" # your main section
    showAllPostsOnHomePage = false
    postsOnHomePage = 10
    tagsOverview = true
    # showProjectsList = true # show projects list by default (if projects data file exists).
    # projectsUrl = "https://github.com/gohugoio" # title link for projects list
    showAllPostsArchive = false
  
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02" # default
	
  
    # Post page settings
    show_updated = false # default
    defaultAuthor = "ErrorPro"

    mathjax = true
    css = ["css/highlight.css", "css/style-dark.css", "css/search.css", "css/cursor.css"]
  
    [params.comments]
      enabled = false # default
      engine = "cactus_comments" # more supported engines will be added.
      [params.comments.cactuscomments]
        siteName = "errorpro" # see https://cactus.chat/ on how to register your site name
        #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
        #serverName = "" # Defaults to cactus.chat
	  
  
    # the value of name should be an valid font awesome icon name (brands type)
    # https://fontawesome.com/icons?d=gallery&s=brands

    [[params.social]]
    name = "facebook"
    link = "https://www.facebook.com/errorpro05"
	[[params.social]]
    name = "instagram"
    link = "https://www.instagram.com/compile.err0r"
	[[params.social]]
	name = "github"
	link = "https://github.com/ja-errorpro"
	[[params.social]]
	name = "discord"
	link = "https://discordapp.com/users/430940209975132160"
    [[params.social]]
    name = "youtube"
    link = "https://bit.ly/3D66h7j"
	[[params.social]]
    name = "google"
    link = "https://g.dev/CompileErr0r"
	[[params.social]]
	name = "twitter"
	link = "https://twitter.com/CompileErr0r"
    [[params.social]]
    name = "email"
    link = "yijiahuang@ja-errorpro.codes"  # no need for "mailto:" in the head
[outputs]
    home = ["HTML", "RSS", "JSON"]
